[project]
name = "ai-agent-auto-applier"
version = "0.1.0"
description = ""
authors = [
    {name = "Henry Rothenberg",email = "hsr205@aol.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "linkedin-api (>=2.3.1,<3.0.0)",
    "pydantic-settings (>=2.14.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
